In [ ]:
#INDEXING AND SORTING DATAFRAMES:

import pandas as pd

df = pd.read_excel(r".../datasets/world_population_excel_workbook.xlsx")

df.set_index(['Continent', 'Country'], inplace=True)

df.sort_index(inplace=True)

df

                            Rank CCA3      Capital  2022 Population  \
Continent     Country
Africa        Algeria         34  DZA      Algiers         44903225
              Angola          42  AGO       Luanda         35588987
              Benin           77  BEN   Porto-Novo         13352864
              Botswana       144  BWA     Gaborone          2630296
              Burkina Faso    58  BFA  Ouagadougou         22673762
...                          ...  ...          ...              ...
South America Paraguay       109  PRY    AsunciÃ³n          6780744
              Peru            44  PER         Lima         34049588
              Suriname       170  SUR   Paramaribo           618040
              Uruguay        133  URY   Montevideo          3422794
              Venezuela       51  VEN      Caracas         28301696

                            2020 Population  2015 Population  2010 Population  \
Continent     Country
Africa        Algeria              43451666         39543154         35856344
              Angola               33428485         28127721         23364185
              Benin                12643123         10932783          9445710
              Botswana              2546402          2305171          2091664
              Burkina Faso         21522626         18718019         16116845
...                                     ...              ...              ...
South America Paraguay              6618695          6177950          5768613
              Peru                 33304756         30711863         29229572
              Suriname               607065           575475           546080
              Uruguay               3429086          3402818          3352651
              Venezuela            28490453         30529716         28715022

                            2000 Population  1990 Population  1980 Population  \
Continent     Country
Africa        Algeria              30774621         25518074         18739378
              Angola               16394062         11828638          8330047
              Benin                 6998023          5133419          3833939
              Botswana              1726985          1341474           938578
              Burkina Faso         11882888          9131361          6932967
...                                     ...              ...              ...
South America Paraguay              5123819          4059195          3078912
              Peru                 26654439         22109099         17492406
              Suriname               478998           412756           375112
              Uruguay               3292224          3117012          2953750
              Venezuela            24427729         19750579         15210443

                            1970 Population  Area (kmÂ²)  Density (per kmÂ²)  \
Continent     Country
Africa        Algeria              13795915      2381741             18.8531
              Angola                6029700      1246700             28.5466
              Benin                 3023443       112622            118.5635
              Botswana               592244       582000              4.5194
              Burkina Faso          5611666       272967             83.0641
...                                     ...          ...                 ...
South America Paraguay              2408787       406752             16.6705
              Peru                 13562371      1285216             26.4933
              Suriname               379918       163820              3.7727
              Uruguay               2790265       181034             18.9069
              Venezuela            11355475       916445             30.8820

                            Growth Rate  World Population Percentage
Continent     Country
Africa        Algeria            1.0164                         0.56
              Angola             1.0315                         0.45
              Benin              1.0274                         0.17
              Botswana           1.0162                         0.03
              Burkina Faso       1.0259                         0.28
...                                 ...                          ...
South America Paraguay           1.0115                         0.09
              Peru               1.0099                         0.43
              Suriname           1.0082                         0.01
              Uruguay            0.9990                         0.04
              Venezuela          1.0036                         0.35

[234 rows x 15 columns]

In [4]:
df.loc["Africa"]

,Rank,CCA3,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,
Algeria,34,DZA,Algiers,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
Angola,42,AGO,Luanda,35588987,33428485,28127721,23364185,16394062,11828638,8330047,6029700,1246700,28.5466,1.0315,0.45
Benin,77,BEN,Porto-Novo,13352864,12643123,10932783,9445710,6998023,5133419,3833939,3023443,112622,118.5635,1.0274,0.17
Botswana,144,BWA,Gaborone,2630296,2546402,2305171,2091664,1726985,1341474,938578,592244,582000,4.5194,1.0162,0.03
Burkina Faso,58,BFA,Ouagadougou,22673762,21522626,18718019,16116845,11882888,9131361,6932967,5611666,272967,83.0641,1.0259,0.28
Burundi,78,BDI,Bujumbura,12889576,12220227,10727148,9126605,6307659,5483793,4312834,3497834,27834,463.0874,1.0270,0.16
Cameroon,53,CMR,Yaounde,27914536,26491087,23012646,19878036,15091594,11430520,8519891,6452787,475442,58.7128,1.0263,0.35
Cape Verde,171,CPV,Praia,593149,582640,552166,521212,458251,364563,317234,287262,4033,147.0739,1.0089,0.01
Central African Republic,117,CAF,Bangui,5579144,5343020,4819333,4660067,3759170,2809221,2415276,2067356,622984,8.9555,1.0224,0.07
Chad,69,TCD,N'Djamena,17723315,16644701,14140274,11894727,8259137,5827069,4408230,3667394,1284000,13.8032,1.0316,0.22
Comoros,163,COM,Moroni,836774,806166,730216,656024,536758,431119,328328,242351,1862,449.3953,1.0184,0.01
DR Congo,15,COD,Kinshasa,99010212,92853164,78656904,66391257,48616317,35987541,26708686,20151733,2344858,42.2244,1.0325,1.24
Djibouti,160,DJI,Djibouti,1120849,1090156,1006259,919199,742033,577173,324121,144379,23200,48.3125,1.0138,0.01
Egypt,14,EGY,Cairo,110990103,107465134,97723799,87252413,71371371,57214630,43748556,34781986,1002450,110.7188,1.0158,1.39
Equatorial Guinea,152,GNQ,Malabo,1674908,1596049,1346973,1094524,684977,465549,282509,316955,28051,59.7094,1.0247,0.02
Eritrea,132,ERI,Asmara,3684032,3555868,3340006,3147727,2392880,2149960,1657982,1272748,117600,31.3268,1.0176,0.05
Eswatini,159,SWZ,Mbabane,1201670,1180655,1133936,1099920,1030496,854011,598564,442865,17364,69.2047,1.0079,0.02
Ethiopia,12,ETH,Addis Ababa,123379924,117190911,102471895,89237791,67031867,47878073,34945469,28308246,1104300,111.7268,1.0257,1.55
Gabon,146,GAB,Libreville,2388992,2292573,2028517,1711105,1272935,983028,749078,597192,267668,8.9252,1.0204,0.03
Gambia,142,GMB,Banjul,2705992,2573995,2253133,1937275,1437539,1040616,718586,528731,10689,253.1567,1.0250,0.03
Ghana,47,GHA,Accra,33475870,32180401,28870939,25574719,19665502,15446982,11865246,8861895,238533,140.3406,1.0196,0.42
Guinea,75,GIN,Conakry,13859341,13205153,11625998,10270728,8336967,6354145,4972609,4222374,245857,56.3716,1.0242,0.17
Guinea-Bissau,149,GNB,Bissau,2105566,2015828,1788919,1567220,1230849,973551,831462,591663,36125,58.2856,1.0218,0.03
Ivory Coast,52,CIV,Yamoussoukro,28160542,26811790,23596741,21120042,16799670,11910540,8303809,5477086,322463,87.3295,1.0248,0.35
Kenya,27,KEN,Nairobi,54027487,51985780,46851488,41517895,30851606,23162269,16187124,11473087,580367,93.0919,1.0193,0.68
Lesotho,147,LSO,Maseru,2305825,2254100,2118521,2022747,1998630,1798997,1407672,1023481,30355,75.9620,1.0107,0.03
Liberia,121,LBR,Monrovia,5302681,5087584,4612329,4019956,2895224,2209731,1932169,1463563,111369,47.6136,1.0210,0.07
Libya,107,LBY,Tripoli,6812341,6653942,6192235,6491988,5154790,4236983,2962720,1909177,1759540,3.8717,1.0114,0.09
Madagascar,50,MDG,Antananarivo,29611714,28225177,24850912,21731053,16216431,11882762,8948162,6639751,587041,50.4423,1.0241,0.37
Malawi,62,MWI,Lilongwe,20405317,19377061,16938942,14718422,11229387,9539665,6267369,4625141,118484,172.2200,1.0259,0.26
Mali,59,MLI,Bamako,22593590,21224040,18112907,15529181,11239101,8945026,7372581,6153587,1240192,18.2178,1.0314,0.28
Mauritania,126,MRT,Nouakchott,4736139,4498604,3946220,3419461,2695003,2006027,1506694,1122198,1030700,4.5951,1.0263,0.06
Mauritius,157,MUS,Port Louis,1299469,1297828,1293153,1283330,1215930,1090290,954865,830115,2040,636.9946,1.0004,0.02
Mayotte,182,MYT,Mamoudzou,326101,305587,249545,211786,159215,92659,52233,35383,374,871.9278,1.0319,0.00
Morocco,40,MAR,Rabat,37457971,36688772,34680458,32464865,28554415,24570814,19678444,15274351,446550,83.8830,1.0103,0.47
Mozambique,48,MOZ,Maputo,32969517,31178239,26843246,23073723,17768505,13303459,11413587,8411676,801590,41.1302,1.0278,0.41
Namibia,145,NAM,Windhoek,2567012,2489098,2282704,2099271,1819141,1369011,975994,754467,825615,3.1092,1.0146,0.03
Niger,54,NER,Niamey,26207977,24333639,20128124,16647543,11622665,8370647,6173177,4669708,1267000,20.6851,1.0378,0.33
Nigeria,6,NGA,Abuja,218541212,208327405,183995785,160952853,122851984,95214257,72951439,55569264,923768,236.5759,1.0241,2.74
Republic of the Congo,114,COG,Brazzaville,5970424,5702174,5064386,4437884,3134030,2385435,1829256,1396989,342000,17.4574,1.0231,0.07
Reunion,161,REU,Saint-Denis,974052,957822,922495,890130,785424,658992,551674,473925,2511,387.9140,1.0082,0.01
Rwanda,76,RWA,Kigali,13776698,13146362,11642959,10309031,8109989,7319962,5247532,3896367,26338,523.0731,1.0234,0.17
Sao Tome and Principe,187,STP,SÃ£o TomÃ©,227380,218641,201124,182138,143714,120343,97210,77583,964,235.8714,1.0192,0.00
Senegal,72,SEN,Dakar,17316449,16436119,14356181,12530121,9704287,7536001,5703869,4367744,196722,88.0250,1.0261,0.22
Seychelles,196,SYC,Victoria,107118,105530,99240,92409,80060,71057,65290,54379,452,236.9867,1.0061,0.00
Sierra Leone,102,SLE,Freetown,8605718,8233969,7314773,6436698,4584067,4325388,3367477,2778557,71740,119.9570,1.0220,0.11
Somalia,70,SOM,Mogadishu,17597511,16537016,13763906,12026649,8721465,6999096,5892224,3720977,637657,27.5971,1.0312,0.22
South Africa,24,ZAF,Pretoria,59893885,58801927,55876504,51784921,46813266,39877570,29463549,22368306,1221037,49.0517,1.0084,0.75
South Sudan,86,SSD,Juba,10913164,10606227,11194299,9714419,6114440,4750817,4192011,3342410,619745,17.6091,1.0153,0.14
Sudan,32,SDN,Khartoum,46874204,44440486,38171178,33739933,26298773,21090886,16673586,11305206,1886068,24.8529,1.0267,0.59
Tanzania,22,TZA,Dodoma,65497748,61704518,52542823,45110527,34463704,26206012,19297659,13618192,945087,69.3034,1.0300,0.82
Togo,100,TGO,LomÃ©,8848699,8442580,7473229,6571855,5008035,3875947,2838110,2197383,56785,155.8281,1.0236,0.11
Tunisia,79,TUN,Tunis,12356117,12161723,11557779,10895063,9893316,8440023,6578156,5047404,163610,75.5218,1.0076,0.15
Uganda,31,UGA,Kampala,47249585,44404611,37477356,32341728,24020697,17586630,13284026,10317212,241550,195.6100,1.0304,0.59
Western Sahara,172,ESH,El AaiÃºn,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
Zambia,63,ZMB,Lusaka,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [5]:
df.loc["Africa", "Benin"]

Rank                                   77
CCA3                                  BEN
Capital                        Porto-Novo
2022 Population                  13352864
2020 Population                  12643123
2015 Population                  10932783
2010 Population                   9445710
2000 Population                   6998023
1990 Population                   5133419
1980 Population                   3833939
1970 Population                   3023443
Area (kmÂ²)                        112622
Density (per kmÂ²)               118.5635
Growth Rate                        1.0274
World Population Percentage          0.17
Name: (Africa, Benin), dtype: object

In [6]:
df.iloc[3]

Rank                                144
CCA3                                BWA
Capital                        Gaborone
2022 Population                 2630296
2020 Population                 2546402
2015 Population                 2305171
2010 Population                 2091664
2000 Population                 1726985
1990 Population                 1341474
1980 Population                  938578
1970 Population                  592244
Area (kmÂ²)                      582000
Density (per kmÂ²)               4.5194
Growth Rate                      1.0162
World Population Percentage        0.03
Name: (Africa, Botswana), dtype: object